Buffer price to Pilot
Zenmo/Local4Local pull request #35
Opened 2024-09-26 12:16 UTC by macano

Only the last commit is part of this PR.
Merge after https://github.com/Zenmo/Local4Local/pull/32.

2024-09-26 12:48 UTC, Erikvv requested changes
Verified as working, just some small feedback.

2024-09-26 12:48 UTC, Erikvv commented on webtool/frontend/src/components/configure.tsx
> +        setPilot(pilot.withBufferPrice(parseFloat(bufferPrice as string) * 0.01))
Dont need to multiply if input and property is both euros.

2024-09-26 12:48 UTC, Erikvv commented on webtool/gradle/common/src/commonMain/kotlin/Pilot.kt
> +    val bufferPrice_EurpkWh: Double,
EurpkWh -> eurpkWh

2024-09-26 12:48 UTC, Erikvv commented on webtool/frontend/src/components/add-dropdown.tsx
> +            <DropdownMenu.Item onSelect={addBufferPrice}>Buffer Price</DropdownMenu.Item>
Buffer Price -> Bufferprijs

2024-09-26 12:48 UTC, Erikvv commented on webtool/frontend/src/components/buffer-price.tsx
> +                    <label className="form-label" htmlFor="bufferPrice_EurpkWh">Onderhoudskosten [€/kWh]</label>
Incorrect label

2024-09-26 12:48 UTC, Erikvv commented on webtool/frontend/src/components/buffer-price.tsx
> +                    <input className="form-input" type="number" id="bufferPrice_EurpkWh" name="bufferPrice_EurpkWh" defaultValue={1000}/>
Too high default. I suggest € 0.01 with step € 0.001

2024-09-26 12:48 UTC, Erikvv commented on webtool/frontend/src/components/buffer-price.tsx
> +        const solarFarm = formData.get("bufferPrice_EurpkWh") as string
copypasta

2024-10-01 13:33 UTC, closed without merging

2024-10-01 13:33 UTC, macano commented
work continue in https://github.com/Zenmo/Local4Local/pull/37